{"name": "Test01: Verify Invalid Login to Parabank", "status": "failed", "statusDetails": {"message": "AssertionError: Verify equals failed, actual result:An internal error has occurred and has been logged. is not equal to expected:The username and password could not be verified.", "trace": "self = <tests_cases.test_web.TestWeb object at 0x0000018A0CDF6720>, user = 'nir', password = '12344'\n\n    @allure.title('Test01: Verify Invalid Login to Parabank')\n    @allure.description('This test verifies that attempting to log in with invalid credentials results in error message.')\n    @pytest.mark.parametrize('user, password', web_flows.testdata)  # get testdata from csv file\n    def test_verify_login_error_parabank(self, user, password):\n        # Attempt to log in with invalid credentials\n        WebFlows.login_parabank(user, password)\n        # Expected error message when login fails\n        expected_error_text = \"The username and password could not be verified.\"\n        # Verify the login error message is displayed correctly\n>       WebFlows.verify_login_parabank(expected_error_text)\n\ntest_web.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\workflows\\web_flows.py:24: in verify_login_parabank\n    Verifications.verify_equals(actual, expected)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nactual = 'An internal error has occurred and has been logged.', expected = 'The username and password could not be verified.'\n\n    @staticmethod\n    @allure.step('Verify that actual value \"{actual}\" equals expected value \"{expected}\"')\n    def verify_equals(actual, expected):\n        print(f'actual is {actual}')\n        print(f'expected is {expected}')\n>       assert actual == expected, f'Verify equals failed, actual result:{actual} is not equal to expected:{expected}'\nE       AssertionError: Verify equals failed, actual result:An internal error has occurred and has been logged. is not equal to expected:The username and password could not be verified.\n\n..\\extensions\\verification.py:13: AssertionError"}, "description": "This test verifies that attempting to log in with invalid credentials results in error message.", "steps": [{"name": "login to Parabank", "status": "passed", "steps": [{"name": "Update text of element with value \"'nir'\"", "status": "passed", "parameters": [{"name": "element", "value": "<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x0000018A0CFE8080>"}, {"name": "text", "value": "'nir'"}], "start": 1725103708273, "stop": 1725103708460}, {"name": "Update text of element with value \"'12344'\"", "status": "passed", "parameters": [{"name": "element", "value": "<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x0000018A0C3FE090>"}, {"name": "text", "value": "'12344'"}], "start": 1725103708475, "stop": 1725103708623}, {"name": "Click on element", "status": "passed", "parameters": [{"name": "element", "value": "<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x0000018A0CFEAA50>"}], "start": 1725103708638, "stop": 1725103709192}], "parameters": [{"name": "username", "value": "'nir'"}, {"name": "password", "value": "'12344'"}], "start": 1725103708216, "stop": 1725103709192}, {"name": "Verify login error message on Parabank", "status": "failed", "statusDetails": {"message": "AssertionError: Verify equals failed, actual result:An internal error has occurred and has been logged. is not equal to expected:The username and password could not be verified.\n", "trace": "  File \"C:\\Automation\\Projects\\selenium3-python\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Projects\\selenium3-python\\workflows\\web_flows.py\", line 24, in verify_login_parabank\n    Verifications.verify_equals(actual, expected)\n  File \"C:\\Automation\\Projects\\selenium3-python\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Projects\\selenium3-python\\extensions\\verification.py\", line 13, in verify_equals\n    assert actual == expected, f'Verify equals failed, actual result:{actual} is not equal to expected:{expected}'\n"}, "steps": [{"name": "Verify that actual value \"'An internal error has occurred and has been logged.'\" equals expected value \"'The username and password could not be verified.'\"", "status": "failed", "statusDetails": {"message": "AssertionError: Verify equals failed, actual result:An internal error has occurred and has been logged. is not equal to expected:The username and password could not be verified.\n", "trace": "  File \"C:\\Automation\\Projects\\selenium3-python\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Projects\\selenium3-python\\extensions\\verification.py\", line 13, in verify_equals\n    assert actual == expected, f'Verify equals failed, actual result:{actual} is not equal to expected:{expected}'\n"}, "parameters": [{"name": "actual", "value": "'An internal error has occurred and has been logged.'"}, {"name": "expected", "value": "'The username and password could not be verified.'"}], "start": 1725103709243, "stop": 1725103709243}], "parameters": [{"name": "expected", "value": "'The username and password could not be verified.'"}], "start": 1725103709192, "stop": 1725103709247}], "attachments": [{"source": "f2731780-cd35-42e2-bea0-e5358283eed3-attachment.png", "type": "image/png"}], "parameters": [{"name": "user", "value": "'nir'"}, {"name": "password", "value": "'12344'"}], "start": 1725103708215, "stop": 1725103709249, "uuid": "4652d9e7-8c91-4d2f-8f2f-467afc84656b", "historyId": "53491008fb1b3f95ae5b5cc4f02f911d", "testCaseId": "c01495944366ff1e48ce06d760bf062a", "fullName": "test_web.TestWeb#test_verify_login_error_parabank", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_web_driver')"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "TestWeb"}, {"name": "host", "value": "DESKTOP-DHGB96Q"}, {"name": "thread", "value": "6896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_web"}]}