{"name": "Test01: Verify Invalid Login to Parabank", "status": "failed", "statusDetails": {"message": "AssertionError: Verify equals failed, actual result:An internal error has occurred and has been logged. is not equal to expected:The username and password could not be verified.", "trace": "self = <tests_cases.test_web.TestWeb object at 0x000001FCE26F0560>, user = 'dafna', password = '12342'\n\n    @allure.title('Test01: Verify Invalid Login to Parabank')\n    @allure.description('This test verifies that attempting to log in with invalid credentials results in error message.')\n    @pytest.mark.parametrize('user, password', web_flows.testdata)  # get testdata from csv file\n    def test_verify_login_error_parabank(self, user, password):\n        # Attempt to log in with invalid credentials\n        WebFlows.login_parabank(user, password)\n        # Expected error message when login fails\n        expected_error_text = \"The username and password could not be verified.\"\n        # Verify the login error message is displayed correctly\n>       WebFlows.verify_login_parabank(expected_error_text)\n\ntest_web.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\workflows\\web_flows.py:24: in verify_login_parabank\n    Verifications.verify_equals(actual, expected)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nactual = 'An internal error has occurred and has been logged.', expected = 'The username and password could not be verified.'\n\n    @staticmethod\n    @allure.step('Verify that actual value \"{actual}\" equals expected value \"{expected}\"')\n    def verify_equals(actual, expected):\n        print(f'actual is {actual}')\n        print(f'expected is {expected}')\n>       assert actual == expected, f'Verify equals failed, actual result:{actual} is not equal to expected:{expected}'\nE       AssertionError: Verify equals failed, actual result:An internal error has occurred and has been logged. is not equal to expected:The username and password could not be verified.\n\n..\\extensions\\verification.py:13: AssertionError"}, "description": "This test verifies that attempting to log in with invalid credentials results in error message.", "steps": [{"name": "login to Parabank", "status": "passed", "steps": [{"name": "Update text of element with value \"'dafna'\"", "status": "passed", "parameters": [{"name": "element", "value": "<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x000001FCE3479A30>"}, {"name": "text", "value": "'dafna'"}], "start": 1725103808685, "stop": 1725103809108}, {"name": "Update text of element with value \"'12342'\"", "status": "passed", "parameters": [{"name": "element", "value": "<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x000001FCE347A480>"}, {"name": "text", "value": "'12342'"}], "start": 1725103809127, "stop": 1725103809365}, {"name": "Click on element", "status": "passed", "parameters": [{"name": "element", "value": "<selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement object at 0x000001FCE343CB90>"}], "start": 1725103809375, "stop": 1725103809912}], "parameters": [{"name": "username", "value": "'dafna'"}, {"name": "password", "value": "'12342'"}], "start": 1725103808551, "stop": 1725103809912}, {"name": "Verify login error message on Parabank", "status": "failed", "statusDetails": {"message": "AssertionError: Verify equals failed, actual result:An internal error has occurred and has been logged. is not equal to expected:The username and password could not be verified.\n", "trace": "  File \"C:\\Automation\\Projects\\selenium3-python\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Projects\\selenium3-python\\workflows\\web_flows.py\", line 24, in verify_login_parabank\n    Verifications.verify_equals(actual, expected)\n  File \"C:\\Automation\\Projects\\selenium3-python\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Projects\\selenium3-python\\extensions\\verification.py\", line 13, in verify_equals\n    assert actual == expected, f'Verify equals failed, actual result:{actual} is not equal to expected:{expected}'\n"}, "steps": [{"name": "Verify that actual value \"'An internal error has occurred and has been logged.'\" equals expected value \"'The username and password could not be verified.'\"", "status": "failed", "statusDetails": {"message": "AssertionError: Verify equals failed, actual result:An internal error has occurred and has been logged. is not equal to expected:The username and password could not be verified.\n", "trace": "  File \"C:\\Automation\\Projects\\selenium3-python\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Projects\\selenium3-python\\extensions\\verification.py\", line 13, in verify_equals\n    assert actual == expected, f'Verify equals failed, actual result:{actual} is not equal to expected:{expected}'\n"}, "parameters": [{"name": "actual", "value": "'An internal error has occurred and has been logged.'"}, {"name": "expected", "value": "'The username and password could not be verified.'"}], "start": 1725103810035, "stop": 1725103810035}], "parameters": [{"name": "expected", "value": "'The username and password could not be verified.'"}], "start": 1725103809912, "stop": 1725103810036}], "attachments": [{"source": "efffb06b-ac9c-40b2-a99b-b22172c39277-attachment.png", "type": "image/png"}], "parameters": [{"name": "user", "value": "'dafna'"}, {"name": "password", "value": "'12342'"}], "start": 1725103808550, "stop": 1725103810037, "uuid": "7338f9bd-c759-45e6-9227-3c491a19f1bc", "historyId": "e1358381c7a936f305ea0a93a563b12f", "testCaseId": "c01495944366ff1e48ce06d760bf062a", "fullName": "test_web.TestWeb#test_verify_login_error_parabank", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_web_driver')"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "TestWeb"}, {"name": "host", "value": "DESKTOP-DHGB96Q"}, {"name": "thread", "value": "12460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_web"}]}