{"name": "Test03: Verify Sending Email to Parabank Support", "status": "broken", "statusDetails": {"message": "TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'", "trace": "request = <SubRequest 'init_web_driver' for <Function test_verify_login_error_parabank[nir-12344]>>\n\n    @pytest.fixture(scope='class')\n    def init_web_driver(request):\n        if get_data('Execute_Applitools').lower() == 'yes':\n>           globals()['driver'] = get_web_driver()\n\ntests_cases\\conftest.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests_cases\\conftest.py:112: in get_web_driver\n    driver = get_edge()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_edge():\n        srv = Service(EdgeChromiumDriverManager().install())  # selenium 4\n>       edge_driver = selenium.webdriver.Edge(service=srv)  # selenium 4\nE       TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'\n\ntests_cases\\conftest.py:144: TypeError"}, "description": "This test verifies that an email successfully sent to Parabank customer support.", "start": 1734710815013, "stop": 1734710815013, "uuid": "0e0e7d8f-e58d-4964-beb4-44847c1abc74", "historyId": "6fbcbfea8a4bc77728e7d5895fd7c78b", "testCaseId": "6fbcbfea8a4bc77728e7d5895fd7c78b", "fullName": "tests_cases.test_web.TestWeb#test_verify_sending_email_to_support", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_web_driver')"}, {"name": "parentSuite", "value": "tests_cases"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "TestWeb"}, {"name": "host", "value": "DESKTOP-DHGB96Q"}, {"name": "thread", "value": "16316-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests_cases.test_web"}]}